import {
  ClassicEditor,
  Essentials,
  Paragraph,
  Heading,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  BlockQuote,
  Indent,
  IndentBlock,
  Undo,
  Alignment,
  Autoformat,
  CodeBlock,
  FindAndReplace,
  Font,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  PictureEditing,
  LinkImage,
  Link,
  AutoLink,
  List,
  RemoveFormat,
  Table,
  TableToolbar,
  WordCount,
} from 'ckeditor5'

class CustomEditor extends ClassicEditor {}

CustomEditor.builtinPlugins = [
  Essentials,
  Paragraph,
  Heading,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  BlockQuote,
  Indent,
  IndentBlock,
  Undo,
  Alignment,
  Autoformat,
  CodeBlock,
  FindAndReplace,
  Font,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  PictureEditing,
  LinkImage,
  Link,
  AutoLink,
  List,
  RemoveFormat,
  Table,
  TableToolbar,
  WordCount,
]

CustomEditor.defaultConfig = {
  licenseKey: 'GPL',
  toolbar: {
    items: [
      'undo',
      'redo',
      '|',
      'heading',
      '|',
      'fontFamily',
      'fontSize',
      'fontColor',
      'fontBackgroundColor',
      '|',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'subscript',
      'superscript',
      'removeFormat',
      '|',
      'alignment',
      '|',
      'bulletedList',
      'numberedList',
      'outdent',
      'indent',
      '|',
      'link',
      'blockQuote',
      'codeBlock',
      'insertTable',
      '|',
      'uploadImage',
      'findAndReplace',
    ],
    shouldNotGroupWhenFull: true,
  },
  heading: {
    options: [
      { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
      { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
      { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
      { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
      { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
    ],
  },
  alignment: {
    options: ['left', 'center', 'right', 'justify'],
  },
  image: {
    resizeUnit: '%',
    resizeOptions: [
      { name: 'resizeImage:25', value: '25', icon: 'small', label: '25%' },
      { name: 'resizeImage:50', value: '50', icon: 'medium', label: '50%' },
      { name: 'resizeImage:75', value: '75', icon: 'large', label: '75%' },
      { name: 'resizeImage:original', value: null, icon: 'original', label: '100%' },
    ],
    toolbar: [
      'imageTextAlternative',
      'toggleImageCaption',
      'linkImage',
      '|',
      'imageStyle:alignLeft',
      'imageStyle:alignCenter',
      'imageStyle:alignRight',
      '|',
      'resizeImage:25',
      'resizeImage:50',
      'resizeImage:75',
      'resizeImage:original',
    ],
  },
  table: {
    contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells'],
  },
  link: {
    addTargetToExternalLinks: true,
    defaultProtocol: 'https://',
  },
  language: 'en',
}

export default CustomEditor
